name: tofpulls
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  getx_core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: getx_core_resources
  json_annotation: ^4.7.0
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
