name: tofpulls
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  beamer: ^1.5.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  getit_core_resources:
    git:
      url: https://github.com/icarohs7/unox-flutter-resmodules
      path: getit_core_resources
  hooks_riverpod: ^2.1.1
  json_annotation: ^4.7.0
  rx_shared_preferences: ^3.0.0
  shared_preferences: ^2.0.15
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
